# Generated by Django 4.2.5 on 2023-09-25 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrachcka_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('printers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Restaurant', to='jrachcka_app.printer')),
            ],
        ),
    ]
