# Generated by Django 4.2.5 on 2023-09-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrachcka_app', '0002_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='printers',
        ),
        migrations.AddField(
            model_name='printer',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='jrachcka_app.restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
